// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AddingtocartTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void addingtocart() {
    driver.Navigate().GoToUrl("http://automationpractice.com/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.LinkText("T-shirts")).Click();
    driver.FindElement(By.CssSelector(".lnk_view > span")).Click();
    driver.FindElement(By.CssSelector(".exclusive > span")).Click();
    driver.FindElement(By.CssSelector(".button-medium > span")).Click();
    driver.FindElement(By.CssSelector(".standard-checkout > span")).Click();
    driver.FindElement(By.CssSelector(".button:nth-child(4) > span")).Click();
    driver.FindElement(By.Id("cgv")).Click();
    driver.FindElement(By.CssSelector(".standard-checkout > span")).Click();
    driver.FindElement(By.LinkText("Pay by bank wire (order processing will be longer)")).Click();
    driver.FindElement(By.CssSelector("#cart_navigation span")).Click();
  }
}
